# ========================
# HMM市场状态识别配置
# ========================


scaler: robust  # 可选: standard, minmax, robust
feature_selection: false
top_k_features: 30
pca_variance_ratio: 0.95  # 可设置为整数 或 float(如0.95)，表示保留的PCA方差比
pca_components: null  # 可设置为整数 或 float(如0.95)，表示保留的PCA方差比

data:
  path: "E:/VesperDecimal/data/raw/indexData/HS300_daily_kline.csv"
  train_start: '2020-01-01'
  train_end: '2023-12-31'
  test_start: '2024-01-01'
  test_end: '2024-12-31'

use_manual_features: false
manual_features:
  - returns_5
  - Volume
  - volatility_20
#  - ma_ratio_20
#  - ma_ratio_60
#  - macd
#  - macd_hist
#  - kdj_k
#  - adx
#  - di_plus
#  - volatility_60
#  - garch_vol
#  - hl_spread
#  - momentum_20
#  - price_range_position
#  - close_zscore_60
#  - Price_Zscore
#  - ma_slope_ratio_10_60
#  - price_ma_corr_60
#  - trend_strength_60
#  - momentum_stability_20

#feature_engineer:

#  pca_variance_ratio: 0.95
#
feature_selection_config:
  enable: true
  n_features: 10
  methods:
    - f_test
    - mutual_info
    - random_forest
    - pca
    - correlation

trainer:
  n_states: 3
  n_components: 4
  covariance_type: full
  n_iter: 100
  tol: 0.01
  verbose: 2
  n_jobs: -1
  max_iter: 300
  k_range: [5, 10, 15, 20, 25, 30, 35, 40]
  state_range: [2, 3, 4, 5, 6, 7, 8, 9, 10]


output:
  model_path: '../models/hmm_pipeline.pkl'
  scalar_path: '../models/scaler.pkl'
  feature_selection_path: '../models/feature_selection.pkl'
  pca_path: '../models/pca_model.pkl'


  feature_analysis_path: '../output/feature_analysis_report.txt'
  emission_matrix_path: '../output/emission_matrix_report.html'
  train_report_path: '../output/train_report.html'
  test_report_path: '../output/test_report.html'

